export const VPN_STATUS_REQUESTED = 'VPN_STATUS_REQUESTED';
export const VPN_STATUS_TOGGLED = 'VPN_STATUS_TOGGLED';
export const VPN_STATUS_RECEIVED = 'VPN_STATUS_RECEIVED';
export const LANGUAGE_SELECTED = 'LANGUAGE_SELECTED';

